CREATE TABLE IF NOT EXISTS articles (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  url TEXT NOT NULL,
  source VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- マイルストーン4: summary, labels(JSONB), thumbnail_urlカラム追加
ALTER TABLE articles ADD COLUMN IF NOT EXISTS summary TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS labels JSONB;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS thumbnail_url TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS published TIMESTAMP;
